FROM alpine:3.23

ENV TZ=UTC

RUN apk add --no-cache \
      ca-certificates \
      iproute2 \
      iputils \
      openssh-client \
      tzdata && \
    cp /usr/share/zoneinfo/UTC /etc/localtime && \
    echo "UTC" > /etc/timezone

COPY entrypoint.sh /tmp/entrypoint.sh

RUN install -D -m 0755 -o root -g root /tmp/entrypoint.sh /usr/local/bin/entrypoint.sh && \
    rm -f /tmp/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
