---
cascade_ingress_clash_tcp_concurrent: true
cascade_ingress_watchdog_interval_seconds: 5
cascade_ingress_ssh_healthcheck_interval: 5s
cascade_ingress_ssh_healthcheck_timeout: 2s
cascade_ingress_ssh_healthcheck_retries: 2
cascade_ingress_ssh_healthcheck_start_period: 5s
cascade_ingress_ssh_startup_timeout_seconds: 180
cascade_ingress_clash_healthcheck_interval: 5s
cascade_ingress_clash_healthcheck_timeout: 2s
cascade_ingress_clash_healthcheck_retries: 2
cascade_ingress_clash_healthcheck_start_period: 90s
cascade_ingress_clash_startup_timeout_seconds: 180
