FROM alpine:3.23

ARG vpn_username={{ ssh_tun_ssh_username }}
ARG user_group=vpnusers
ARG public_ed25519_key
ARG network_vpn_gateway_ipv4
ARG network_vpn_gateway_cidr_ipv4
ARG network_vpn_interface={{ ssh_tun_network_interface }}
ARG network_vpn_subnet_cidr_ipv4
ARG network_container_vpn_ipv4
ARG vpn_tun_mtu={{ ssh_tun_tun_mtu }}

ENV vpn_username="${vpn_username}"
ENV user_group="${user_group}"
ENV public_ed25519_key="${public_ed25519_key}"
ENV network_vpn_gateway_ipv4="${network_vpn_gateway_ipv4}"
ENV network_vpn_gateway_cidr_ipv4="${network_vpn_gateway_cidr_ipv4}"
ENV network_vpn_interface="${network_vpn_interface}"
ENV network_vpn_subnet_cidr_ipv4="${network_vpn_subnet_cidr_ipv4}"
ENV network_container_vpn_ipv4="${network_container_vpn_ipv4}"
ENV vpn_tun_mtu="${vpn_tun_mtu}"
ENV TZ=UTC

RUN apk add --no-cache \
      ca-certificates \
      iproute2 \
      iptables \
      openssh-server \
      shadow \
      tzdata && \
    cp /usr/share/zoneinfo/UTC /etc/localtime && \
    echo "UTC" > /etc/timezone

RUN groupadd "${user_group}" && \
    useradd -M -s /sbin/nologin "${vpn_username}" && \
    usermod -p '*' "${vpn_username}" && \
    usermod -aG "${user_group}" "${vpn_username}" && \
    install -d -m 0755 -o root -g root /var/ssh && \
    install -d -m 0700 -o "${vpn_username}" -g "${user_group}" "/var/ssh/${vpn_username}" && \
    cat <<-EOS | install -D -m 0600 -o "${vpn_username}" -g "${user_group}" /dev/stdin "/var/ssh/${vpn_username}/authorized_keys"
${public_ed25519_key}
EOS

RUN cat <<-CONF | install -D -m 0644 -o root -g root /dev/stdin /etc/ssh/sshd_config
Protocol 2
MaxSessions 2
ListenAddress ${network_container_vpn_ipv4}:22
PermitRootLogin no
PermitTunnel yes
Compression no
UseDNS no
PasswordAuthentication no
LoginGraceTime 10
IgnoreRhosts yes
HostbasedAuthentication no
AllowGroups ${user_group}
PermitOpen none
MaxAuthTries 3
StrictModes yes
GatewayPorts no
MaxStartups 5:30:20
TCPKeepAlive no
ClientAliveCountMax 3
ClientAliveInterval 20
X11Forwarding no
AddressFamily inet
PrintMotd no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PermitUserEnvironment no
PermitUserRC no
RekeyLimit 512M 1h
AcceptEnv LANG LC_*
AllowTcpForwarding yes
AllowAgentForwarding no
AuthenticationMethods publickey
PubkeyAuthentication yes
HostKey /etc/ssh/ssh_host_ed25519_key
HostKeyAlgorithms ssh-ed25519
Ciphers aes256-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com
KexAlgorithms mlkem768x25519-sha256,sntrup761x25519-sha512,sntrup761x25519-sha512@openssh.com
AuthorizedKeysFile /var/ssh/%u/authorized_keys
LogLevel ERROR
SyslogFacility AUTHPRIV
Subsystem sftp /bin/false
CONF

RUN install -D -m 0755 -o root -g root /dev/stdin /usr/local/bin/healthcheck <<'EOS'
#!/bin/sh
ss -ltn "( sport = :22 )" >/dev/null 2>&1 || exit 1
ip addr show "${network_vpn_interface}" >/dev/null 2>&1 || exit 1
ip addr show "${network_vpn_interface}" | grep -q "${network_vpn_gateway_cidr_ipv4}" || exit 1
ip route show | grep -q "${network_vpn_subnet_cidr_ipv4}" || exit 1
exit 0
EOS

RUN install -D -m 0755 -o root -g root /dev/stdin /usr/local/bin/vpn <<'EOS'
#!/bin/sh
set -eu
install -d -m 0755 -o root -g root /run/sshd
if [ ! -s /etc/ssh/ssh_host_ed25519_key ]; then
    ssh-keygen -t ed25519 -N '' -f /etc/ssh/ssh_host_ed25519_key >/dev/null
fi
ip link show "${network_vpn_interface}" >/dev/null 2>&1 || ip tuntap add dev "${network_vpn_interface}" mode tun user "${vpn_username}"
ip addr flush dev "${network_vpn_interface}" >/dev/null 2>&1 || true
ip addr add "${network_vpn_gateway_cidr_ipv4}" dev "${network_vpn_interface}"
ip link set dev "${network_vpn_interface}" up mtu "${vpn_tun_mtu}"
iptables -t nat -C POSTROUTING -s "${network_vpn_subnet_cidr_ipv4}" ! -o "${network_vpn_interface}" -j MASQUERADE 2>/dev/null || iptables -t nat -A POSTROUTING -s "${network_vpn_subnet_cidr_ipv4}" ! -o "${network_vpn_interface}" -j MASQUERADE
iptables -C FORWARD -i "${network_vpn_interface}" -j ACCEPT 2>/dev/null || iptables -A FORWARD -i "${network_vpn_interface}" -j ACCEPT
iptables -C FORWARD -o "${network_vpn_interface}" -j ACCEPT 2>/dev/null || iptables -A FORWARD -o "${network_vpn_interface}" -j ACCEPT
iptables -t mangle -C FORWARD -o "${network_vpn_interface}" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || iptables -t mangle -A FORWARD -o "${network_vpn_interface}" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
iptables -t mangle -C FORWARD -i "${network_vpn_interface}" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || iptables -t mangle -A FORWARD -i "${network_vpn_interface}" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
exec /usr/sbin/sshd -D
EOS

EXPOSE 22
ENTRYPOINT ["/usr/local/bin/vpn"]
