
---
- name: Deploy egress stack
  hosts: egress
  become: true
  vars_files:
    - group_vars/egress.yml
  roles:
    - role: system_base
      vars:
        system_base_docker_updater_name: nitka-egress
        system_base_docker_updater_compose_file: "{{ egress_remote_dir }}/compose.yml"
    - role: transports/ssh_tun
      vars:
        ssh_tun_endpoint: server
    - egress
