---
- name: Deploy ingress stack
  hosts: ingress
  become: true
  vars_files:
    - group_vars/egress.yml
    - group_vars/ingress.yml
    - routing/rules.yml
  roles:
    - role: system_base
      vars:
        system_base_docker_updater_name: nitka-ingress
        system_base_docker_updater_compose_file: "{{ ingress_remote_dir }}/compose.yml"
    - role: transports/ssh_tun
      vars:
        ssh_tun_endpoint: client
    - ingress
