---
- name: Deploy reverse VPN server on the primary ingress node
  hosts: ingress
  become: true
  vars_files:
    - group_vars/ingress.yml
    - group_vars/egress.yml
    - group_vars/reverse.yml
    - ../routing/reverse_vpn_conf/rules.yml
  roles:
    - role: system_base
      vars:
        system_base_docker_updater_name: nitka-reverse-egress
        system_base_docker_updater_compose_file: "{{ egress_remote_dir }}/compose.yml"
        system_base_docker_updater_calendar: "*-*-* 03:00"
        system_base_docker_updater_services:
          - service: ssh_tun_server
            container: nitka-reverse-ssh-tun-server
            image_type: build
            base_image: alpine:3.23
            cascade_restart:
              - unbound
          - service: unbound
            container: nitka-reverse-unbound
            image_type: build
            base_image: alpine:3.23
    - role: transports/ssh_tun
      vars:
        ssh_tun_endpoint: server
    - role: egress

- name: Deploy reverse VPN client on the primary egress node
  hosts: egress
  become: true
  vars_files:
    - group_vars/egress.yml
    - group_vars/ingress.yml
    - group_vars/reverse.yml
    - ../routing/reverse_vpn_conf/rules.yml
  roles:
    - role: system_base
      vars:
        system_base_docker_updater_name: nitka-reverse-ingress
        system_base_docker_updater_compose_file: "{{ ingress_remote_dir }}/compose.yml"
        system_base_docker_updater_calendar: "*-*-* 03:20"
        system_base_docker_updater_services:
          - service: ssh_tun_client
            container: nitka-reverse-ssh-tun-client
            image_type: build
            base_image: alpine:3.23
            cascade_restart:
              - clashrs
              - xray
          - service: clashrs
            container: nitka-reverse-clashrs
            image_type: external
            image: local/clash-rs:latest
            release_repo: Watfaq/clash-rs
            release_image_template: ghcr.io/watfaq/clash-rs:latest
            cascade_restart:
              - xray
          - service: xray
            container: nitka-reverse-xray
            image_type: external
            image: local/xray-core:auto
            release_repo: XTLS/Xray-core
            release_image_template: ghcr.io/xtls/xray-core:{tag_no_v}
    - role: transports/ssh_tun
      vars:
        ssh_tun_endpoint: client
    - role: ingress
